### PR TITLE
docs(fn-etl): add extract-message sequence

### PR DESCRIPTION
**Pull request by Garma00**
This PR is based on #39 

#### List of Changes

* Add a new directory `docs/` inside the `etl-func`;
* Add a new sequence diagram describing the wanted behavior  of this function;

#### Motivation and Context

I added this new sequence so we can use it in the DR and we can discuss about the expected behavior.

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by acuiuli** [comment]
Why didn't you put the diagrams inside the docs folder in the root?

**Comment by Garma00** [comment]
> Why didn't you put the diagrams inside the docs folder in the root?

I believe that is better to separate the documentation of the apps but we can discuss about this

**Comment by acuiuli** [comment]
> > Why didn't you put the diagrams inside the docs folder in the root?
> 
> I believe that is better to separate the documentation of the apps but we can discuss about this

I prefer the `docs` folder in the root but we need to decide on a standard and stick to it imho. Since we have also documentations that, right now, is not associated to an app (since io-fn-services is not migrated) I fear that we will end up with documentations scattered all over the place

**Comment by Garma00** [comment]
I will open another PR based on the main branch soon where I'll add also the business logic.

**Pull request closed without merging**
